name: bbti
description: A new Flutter project.
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+3

environment:
  sdk: '>=3.0.3 <4.0.0'
dependencies:
  flutter:
    sdk: flutter
  flutter_native_contact_picker: ^0.0.4
  intl: ^0.17.0
  time_range: ^1.1.0
  cupertino_icons: ^1.0.2
  flutter_barcode_scanner: ^2.0.0
  google_fonts: ^5.1.0
  network_info_plus: ^4.0.1
  connectivity_plus:
  permission_handler: ^10.4.2
  open_settings: ^2.0.2
  dio: ^5.2.1+1
  flutter_secure_storage: ^8.0.0
  pin_code_fields: ^8.0.1
  qr_flutter: ^4.1.0
  share_plus: ^7.0.2
  flutter_launcher_icons: ^0.13.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/BBT_LOGO_2.png"
  min_sdk_android: 21 


flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
  fonts:
    - family: OpenSans
      fonts:
        - asset: assets/fonts/OpenSans-Bold.ttf
        - asset: assets/fonts/OpenSans-Medium.ttf
